load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = ["gitchanges.go"],
    importpath = "github.com/jaeyeom/experimental/devtools/docsync/internal/gitchanges",
    visibility = ["//devtools/docsync:__subpackages__"],
    deps = ["@com_github_jaeyeom_go_cmdexec//:go_default_library"],
)

go_test(
    name = "go_default_test",
    srcs = ["gitchanges_test.go"],
    embed = [":go_default_library"],
    deps = ["@com_github_jaeyeom_go_cmdexec//:go_default_library"],
)
