load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = ["runlog.go"],
    importpath = "github.com/jaeyeom/experimental/devtools/prsync/internal/runlog",
    visibility = ["//devtools/prsync:__subpackages__"],
)

go_test(
    name = "go_default_test",
    srcs = ["runlog_test.go"],
    embed = [":go_default_library"],
)
