version: "2"
linters:
  enable:
    - depguard
    - gocritic
    - godot
    - gosec
    - iface
    - revive
    - staticcheck
    - wrapcheck
  disable:
    - testpackage
  settings:
    staticcheck:
      checks: ["all"]
    iface:
      enable:
        - identical
        - unused
        - opaque
    depguard:
      rules:
        Base:
          list-mode: lax
          files:
            - "$all"
          deny:
            - pkg: "log$"
              desc: use log/slog instead
            - pkg: "io/ioutil"
              desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
        Main:
          list-mode: strict
          files:
            - "$all"
            - "!$test"
          allow:
            - $gostd
            - github.com/google/uuid
            - "github.com/jaeyeom/experimental"
            - "github.com/jaeyeom/sugo"
            - github.com/slack-go/slack
            - gopkg.in/yaml.v3
            - modernc.org/sqlite
            - github.com/spf13/cobra
            - github.com/spf13/viper
            - github.com/mattn/go-sqlite3
          deny:
            - pkg: "github.com/leanovate/gopter"
              desc: gopter is for test only
            - pkg: "github.com/sirupsen/logrus"
              desc: use log/slog instead
        Test:
          list-mode: lax
          files:
            - "$test"
          deny:
            - pkg: "github.com/stretchr/testify"
              desc: "Please use standard library for tests"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - path: _test\.go
        linters:
          - cyclop
          - funlen
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
