# Author: Jaehyun Yeom
#
# Description:
#   Coffee example build file

{exec} = require 'child_process'

task 'build:all', 'Rebuild all coffee to js.', (options) ->
  exec 'coffee --compile lib/*.coffee', (err, stdout, stderr) ->
    throw err if err
    console.log stdout + stderr

task 'test:all', 'Tests all targets.', (options) ->
  invoke 'test:unittest_test'
  invoke 'test:merge_sort_test'
  invoke 'test:linked_list_test'

task 'test:unittest_test', 'Tests unittest framework.', (options) ->
  require './lib/unittest_test'

task 'test:merge_sort_test', 'Tests merge_sort code.', (options) ->
  require './lib/merge_sort_test'

task 'test:linked_list_test', 'Tests linked_list code.', (options) ->
  require './lib/linked_list_test'

task 'clean', 'Remove all compiled js files.', (options) ->
  exec 'rm -f lib/*.js', (err, stdout, stderr) ->
    throw err if err
    console.log stdout + stderr
