load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    importpath = "github.com/jaeyeom/experimental/devtools/linters/cmd/unnecessary-interface-assertion-linter",
    visibility = ["//visibility:private"],
    deps = ["//devtools/linters/unnecessaryinterfaceassertion:go_default_library"],
)

go_binary(
    name = "unnecessary-interface-assertion-linter",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "go_default_test",
    srcs = ["main_test.go"],
    embed = [":go_default_library"],
    deps = ["//devtools/linters/unnecessaryinterfaceassertion:go_default_library"],
)
