---
- import_playbook: setup-user-go-bin-directory.yml

- name: Ensure buildozer is present
  hosts: all
  tasks:
    - name: Include guard for buildozer playbook
      block:
        - name: Stop early if the buildozer playbook is already included
          meta: end_play
          when: buildozer_playbook_imported is defined
        - name: Ensure the buildozer playbook is not included
          set_fact:
            buildozer_playbook_imported: true
          when: buildozer_playbook_imported is not defined

    - name: Check if buildozer is installed
      shell: go version -m $(command -v buildozer) | grep '^\s*mod\s'
      register: buildozer_installed
      ignore_errors: yes
      changed_when: False

    - name: Extract buildozer version
      block:
        - name: Set buildozer facts
          set_fact:
            buildozer_module_path: "{{ buildozer_installed.stdout.split()[1] }}"
            buildozer_module_version: "{{ buildozer_installed.stdout.split()[2] }}"
        - name: Determine the latest buildozer version
          command: go list -m -f "{{ '{{' }}.Version {{ '}}' }}" "{{ buildozer_module_path }}@latest"
          register: buildozer_latest
          ignore_errors: yes
          changed_when: False

        - name: Debug module path and version
          debug:
            msg: "{{ buildozer_module_path }} {{ buildozer_module_version }} => {{ buildozer_latest.stdout }}"
      rescue:
        - name: Clear buildozer facts
          set_fact:
            buildozer_module_path: ""
            buildozer_module_version: ""

    - name: Upgrade buildozer
      command: go install github.com/bazelbuild/buildtools/buildozer@latest
      when: buildozer_module_version is not defined or buildozer_module_version == "" or buildozer_module_version != buildozer_latest.stdout
