---
- import_playbook: setup-cargo.yml
- import_playbook: cargo-install-update.yml

- name: Ensure cargo-outdated is present
  hosts: all
  tasks:
    - name: Include guard for cargo-outdated playbook
      block:
        - name: Stop early if the cargo-outdated playbook is already included
          meta: end_play
          when: cargo_outdated_playbook_imported is defined
        - name: Ensure the cargo-outdated playbook is not included
          set_fact:
            cargo_outdated_playbook_imported: true
          when: cargo_outdated_playbook_imported is not defined

    - name: Check if cargo-outdated is installed
      shell: command -v cargo-outdated
      register: cargo_outdated_installed
      ignore_errors: yes
      changed_when: False

    - name: Install cargo-outdated using Cargo
      command: cargo install cargo-outdated
      when: cargo_outdated_installed.rc != 0

    - name: Update cargo-outdated to latest version
      command: cargo install-update cargo-outdated
      when: cargo_outdated_installed.rc == 0
