---
- import_playbook: rustc.yml

- name: Ensure cargo-update is present
  hosts: all
  tasks:
    - name: Include guard for cargo-update playbook
      block:
        - name: Stop early if the cargo-update playbook is already included
          meta: end_play
          when: cargo_update_playbook_imported is defined
        - name: Ensure the cargo-update playbook is not included
          set_fact:
            cargo_update_playbook_imported: true
          when: cargo_update_playbook_imported is not defined

    - name: Check if cargo-update is installed
      shell: command -v cargo-update
      register: cargo_update_installed
      ignore_errors: yes
      changed_when: False

    - name: Install cargo-update using Cargo
      command: cargo install cargo-update
      when: cargo_update_installed.rc != 0
