---
- import_playbook: setup-cargo.yml

- name: Ensure cargo-install-update is present
  hosts: all
  tasks:
    - name: Include guard for cargo-install-update playbook
      block:
        - name: Stop early if the cargo-install-update playbook is already included
          meta: end_play
          when: cargo_install_update_playbook_imported is defined
        - name: Ensure the cargo-install-update playbook is not included
          set_fact:
            cargo_install_update_playbook_imported: true
          when: cargo_install_update_playbook_imported is not defined

    - name: Check if cargo-install-update is installed
      shell: command -v cargo-install-update
      register: cargo_install_update_installed
      ignore_errors: yes
      changed_when: False

    - name: Install cargo-install-update using Cargo
      command: cargo install cargo-update
      when: cargo_install_update_installed.rc != 0

    - name: Update cargo-install-update to latest version
      command: cargo install-update cargo-update
      when: cargo_install_update_installed.rc == 0
