---
- name: Ensure curl is present
  hosts: all
  tasks:
    - name: Include guard for curl playbook
      block:
        - name: Stop early if the curl playbook is already included
          meta: end_play
          when: curl_playbook_imported is defined
        - name: Ensure the curl playbook is not included
          set_fact:
            curl_playbook_imported: true
          when: curl_playbook_imported is not defined

    - name: Ensure curl is present on MacOS
      community.general.homebrew:
        name: curl
        state: present
      when: ansible_facts['os_family'] == "Darwin"

    - name: Ensure curl is present on non-Termux, non-MacOS systems
      package:
        name: curl
        state: present
      when: ansible_env.TERMUX_VERSION is not defined and ansible_facts['os_family'] != "Darwin"
      become: yes

    - name: Ensure curl is present on Termux
      block:
        - name: Check if curl is installed
          shell: command -v curl
          changed_when: False
      rescue:
        - name: Install curl on Termux
          command: pkg install -y curl
      when: ansible_env.TERMUX_VERSION is defined
