---
- import_playbook: "go.yml"

- name: Ensure fillstruct is present
  hosts: all
  tasks:
    - name: Ensure fillstruct is present
      command: go install github.com/davidrjenni/reftools/cmd/fillstruct@latest
