---
- import_playbook: setup-user-go-bin-directory.yml

- name: Ensure fillstruct is present
  hosts: all
  tasks:
    - name: Include guard for fillstruct playbook
      block:
        - name: Stop early if the fillstruct playbook is already included
          meta: end_play
          when: fillstruct_playbook_imported is defined
        - name: Ensure the fillstruct playbook is not included
          set_fact:
            fillstruct_playbook_imported: true
          when: fillstruct_playbook_imported is not defined

    - name: Check if fillstruct is installed
      shell: go version -m $(command -v fillstruct) | grep '^\s*mod\s'
      register: fillstruct_installed
      ignore_errors: yes
      changed_when: False

    - name: Extract fillstruct version
      block:
        - name: Set fillstruct facts
          set_fact:
            fillstruct_module_path: "{{ fillstruct_installed.stdout.split()[1] }}"
            fillstruct_module_version: "{{ fillstruct_installed.stdout.split()[2] }}"
        - name: Determine the latest fillstruct version
          command: go list -m -f "{{ '{{' }}.Version {{ '}}' }}" "{{ fillstruct_module_path }}@latest"
          register: fillstruct_latest
          ignore_errors: yes
          changed_when: False

        - name: Debug module path and version
          debug:
            msg: "{{ fillstruct_module_path }} {{ fillstruct_module_version }} => {{ fillstruct_latest.stdout }}"
      rescue:
        - name: Clear fillstruct facts
          set_fact:
            fillstruct_module_path: ""
            fillstruct_module_version: ""

    - name: Upgrade fillstruct
      command: go install github.com/davidrjenni/reftools/cmd/fillstruct@latest
      when: fillstruct_module_version is not defined or fillstruct_module_version == "" or fillstruct_module_version != fillstruct_latest.stdout
