---
- import_playbook: npm.yml

- name: Ensure gemini-cli is present
  hosts: all
  tasks:
    - name: Include guard for gemini-cli playbook
      block:
        - name: Stop early if the gemini-cli playbook is already included
          meta: end_play
          when: gemini_cli_playbook_imported is defined
        - name: Ensure the gemini-cli playbook is not included
          set_fact:
            gemini_cli_playbook_imported: true
          when: gemini_cli_playbook_imported is not defined

    - name: Check if gemini-cli is installed
      shell: command -v gemini-cli
      register: gemini_cli_installed
      ignore_errors: yes
      changed_when: False

    - name: Install gemini-cli using npm
      command: npm install -g @google/gemini-cli
      when: gemini_cli_installed.rc != 0
