---
- name: Ensure go is present
  hosts: all
  tasks:
    - name: Ensure go is present on non-Termux systems
      package:
        name: golang-go
        state: present
      when: ansible_env.TERMUX_VERSION is not defined
      become: yes

    - name: Ensure go is present on Termux
      block:
        - name: Check if go is installed
          shell: command -v go
          changed_when: False
      rescue:
        - name: Install go on Termux
          command: pkg install -y golang
      when: ansible_env.TERMUX_VERSION is defined
