---
- import_playbook: "go.yml"

- name: Ensure godef is present
  hosts: all
  tasks:
    - name: Check if godef is installed
      shell: go version -m $(command -v godef) | grep '^\s*mod\s'
      register: godef_installed
      ignore_errors: yes
      changed_when: False

    - name: Extract module path
      set_fact:
        module_path: "{{ godef_installed.stdout.split()[1] }}"
        module_version: "{{ godef_installed.stdout.split()[2] }}"

    - name: Determine the latest godef version
      command: go list -m -f "{{ '{{' }}.Version {{ '}}' }}" "{{ module_path }}@latest"
      register: godef_latest
      ignore_errors: yes
      changed_when: False

    - name: Debug module path and version
      debug:
        msg: "{{ module_path }} {{ module_version }} => {{ godef_latest.stdout }}"

    - name: Ensure godef is present
      command: go install github.com/rogpeppe/godef@latest
      when: module_version is not defined or module_version != godef_latest.stdout
