---
- import_playbook: setup-user-go-bin-directory.yml

- name: Ensure godef is present
  hosts: all
  tasks:
    - name: Check if godef is installed
      shell: go version -m $(command -v godef) | grep '^\s*mod\s'
      register: godef_installed
      ignore_errors: yes
      changed_when: False

    - name: Extract godef version
      block:
        - name: Set godef facts
          set_fact:
            godef_module_path: "{{ godef_installed.stdout.split()[1] }}"
            godef_module_version: "{{ godef_installed.stdout.split()[2] }}"
        - name: Determine the latest godef version
          command: go list -m -f "{{ '{{' }}.Version {{ '}}' }}" "{{ godef_module_path }}@latest"
          register: godef_latest
          ignore_errors: yes
          changed_when: False

        - name: Debug module path and version
          debug:
            msg: "{{ godef_module_path }} {{ godef_module_version }} => {{ godef_latest.stdout }}"
      rescue:
        - name: Clear godef facts
          set_fact:
            godef_module_path: ""
            godef_module_version: ""

    - name: Upgrade godef
      command: go install github.com/rogpeppe/godef@latest
      when: godef_module_version is not defined or godef_module_version == "" or godef_module_version != godef_latest.stdout
