---
- import_playbook: "go.yml"

- name: Ensure godoctor is present
  hosts: all
  tasks:
    - name: Check if godoctor is installed
      shell: go version -m $(command -v godoctor) | grep '^\s*mod\s'
      register: godoctor_installed
      ignore_errors: yes
      changed_when: False

    - name: Extract module path
      set_fact:
        module_path: "{{ godoctor_installed.stdout.split()[1] }}"
        module_version: "{{ godoctor_installed.stdout.split()[2] }}"

    - name: Determine the latest godoctor version
      command: go list -m -f "{{ '{{' }}.Version {{ '}}' }}" "{{ module_path }}@latest"
      register: godoctor_latest
      ignore_errors: yes
      changed_when: False

    - name: Debug module path and version
      debug:
        msg: "{{ module_path }} {{ module_version }} => {{ godoctor_latest.stdout }}"

    - name: Ensure godoctor is present
      command: go install github.com/godoctor/godoctor@latest
      when: module_version is not defined or module_version != godoctor_latest.stdout
