---
- import_playbook: "go.yml"

- name: Ensure godoc is present
  hosts: all
  tasks:
    - name: Check if godoc is installed
      shell: go version -m $(command -v godoc) | grep '^\s*mod\s'
      register: godoc_installed
      ignore_errors: yes
      changed_when: False

    - name: Extract godoc version
      block:
        - name: Set godoc facts
          set_fact:
            godoc_module_path: "{{ godoc_installed.stdout.split()[1] }}"
            godoc_module_version: "{{ godoc_installed.stdout.split()[2] }}"
        - name: Determine the latest godoc version
          command: go list -m -f "{{ '{{' }}.Version {{ '}}' }}" "{{ godoc_module_path }}@latest"
          register: godoc_latest
          ignore_errors: yes
          changed_when: False

        - name: Debug module path and version
          debug:
            msg: "{{ godoc_module_path }} {{ godoc_module_version }} => {{ godoc_latest.stdout }}"
      rescue:
        - name: Clear godoc facts
          set_fact:
            godoc_module_path: ""
            godoc_module_version: ""

    - name: Upgrade godoc
      command: go install golang.org/x/tools/cmd/godoc@latest
      when: godoc_module_version is not defined or godoc_module_version == "" or godoc_module_version != godoc_latest.stdout
