---
- import_playbook: "go.yml"

- name: Ensure godoc is present
  hosts: all
  tasks:
    - name: Check if godoc is installed
      shell: go version -m $(command -v godoc) | grep '^\s*mod\s'
      register: godoc_installed
      ignore_errors: yes
      changed_when: False

    - name: Extract module path
      set_fact:
        module_path: "{{ godoc_installed.stdout.split()[1] }}"
        module_version: "{{ godoc_installed.stdout.split()[2] }}"

    - name: Determine the latest godoc version
      command: go list -m -f "{{ '{{' }}.Version {{ '}}' }}" "{{ module_path }}@latest"
      register: godoc_latest
      ignore_errors: yes
      changed_when: False

    - name: Debug module path and version
      debug:
        msg: "{{ module_path }} {{ module_version }} => {{ godoc_latest.stdout }}"

    - name: Ensure godoc is present
      command: go install golang.org/x/tools/cmd/godoc@latest
      when: module_version is not defined or module_version != godoc_latest.stdout
