---
- import_playbook: "go.yml"

- name: Ensure goimports is present
  hosts: all
  tasks:
    - name: Check if goimports is installed
      shell: go version -m $(command -v goimports) | grep '^\s*mod\s'
      register: goimports_installed
      ignore_errors: yes
      changed_when: False

    - name: Extract module path
      set_fact:
        module_path: "{{ goimports_installed.stdout.split()[1] }}"
        module_version: "{{ goimports_installed.stdout.split()[2] }}"

    - name: Determine the latest goimports version
      command: go list -m -f "{{ '{{' }}.Version {{ '}}' }}" "{{ module_path }}@latest"
      register: goimports_latest
      ignore_errors: yes
      changed_when: False

    - name: Debug module path and version
      debug:
        msg: "{{ module_path }} {{ module_version }} => {{ goimports_latest.stdout }}"

    - name: Ensure goimports is present
      command: go install golang.org/x/tools/cmd/goimports@latest
      when: module_version is not defined or module_version != goimports_latest.stdout
