---
- import_playbook: "go.yml"

- name: Ensure gomodifytags is present
  hosts: all
  tasks:
    - name: Check if gomodifytags is installed
      shell: go version -m $(command -v gomodifytags) | grep '^\s*mod\s'
      register: gomodifytags_installed
      ignore_errors: yes
      changed_when: False

    - name: Extract module path
      set_fact:
        module_path: "{{ gomodifytags_installed.stdout.split()[1] }}"
        module_version: "{{ gomodifytags_installed.stdout.split()[2] }}"

    - name: Determine the latest gomodifytags version
      command: go list -m -f "{{ '{{' }}.Version {{ '}}' }}" "{{ module_path }}@latest"
      register: gomodifytags_latest
      ignore_errors: yes
      changed_when: False

    - name: Debug module path and version
      debug:
        msg: "{{ module_path }} {{ module_version }} => {{ gomodifytags_latest.stdout }}"

    - name: Ensure gomodifytags is present
      command: go install github.com/fatih/gomodifytags@latest
      when: module_version is not defined or module_version != gomodifytags_latest.stdout
