---
- import_playbook: setup-user-go-bin-directory.yml

- name: Ensure gomodifytags is present
  hosts: all
  tasks:
    - name: Check if gomodifytags is installed
      shell: go version -m $(command -v gomodifytags) | grep '^\s*mod\s'
      register: gomodifytags_installed
      ignore_errors: yes
      changed_when: False

    - name: Extract gomodifytags version
      block:
        - name: Set gomodifytags facts
          set_fact:
            gomodifytags_module_path: "{{ gomodifytags_installed.stdout.split()[1] }}"
            gomodifytags_module_version: "{{ gomodifytags_installed.stdout.split()[2] }}"
        - name: Determine the latest gomodifytags version
          command: go list -m -f "{{ '{{' }}.Version {{ '}}' }}" "{{ gomodifytags_module_path }}@latest"
          register: gomodifytags_latest
          ignore_errors: yes
          changed_when: False

        - name: Debug module path and version
          debug:
            msg: "{{ gomodifytags_module_path }} {{ gomodifytags_module_version }} => {{ gomodifytags_latest.stdout }}"
      rescue:
        - name: Clear gomodifytags facts
          set_fact:
            gomodifytags_module_path: ""
            gomodifytags_module_version: ""

    - name: Upgrade gomodifytags
      command: go install github.com/fatih/gomodifytags@latest
      when: gomodifytags_module_version is not defined or gomodifytags_module_version == "" or gomodifytags_module_version != gomodifytags_latest.stdout
