---
- import_playbook: "go.yml"

- name: Ensure gopkgs is present
  hosts: all
  tasks:
    - name: Check if gopkgs is installed
      shell: go version -m $(command -v gopkgs) | grep '^\s*mod\s'
      register: gopkgs_installed
      ignore_errors: yes
      changed_when: False

    - name: Extract module path
      set_fact:
        module_path: "{{ gopkgs_installed.stdout.split()[1] }}"
        module_version: "{{ gopkgs_installed.stdout.split()[2] }}"

    - name: Determine the latest gopkgs version
      command: go list -m -f "{{ '{{' }}.Version {{ '}}' }}" "{{ module_path }}@latest"
      register: gopkgs_latest
      ignore_errors: yes
      changed_when: False

    - name: Debug module path and version
      debug:
        msg: "{{ module_path }} {{ module_version }} => {{ gopkgs_latest.stdout }}"

    - name: Ensure gopkgs is present
      command: go install github.com/uudashr/gopkgs/v2/cmd/gopkgs@latest
      when: module_version is not defined or module_version != gopkgs_latest.stdout
