---
- import_playbook: "go.yml"

- name: Ensure gorename is present
  hosts: all
  tasks:
    - name: Check if gorename is installed
      shell: go version -m $(command -v gorename) | grep '^\s*mod\s'
      register: gorename_installed
      ignore_errors: yes
      changed_when: False

    - name: Extract module path
      set_fact:
        module_path: "{{ gorename_installed.stdout.split()[1] }}"
        module_version: "{{ gorename_installed.stdout.split()[2] }}"

    - name: Determine the latest gorename version
      command: go list -m -f "{{ '{{' }}.Version {{ '}}' }}" "{{ module_path }}@latest"
      register: gorename_latest
      ignore_errors: yes
      changed_when: False

    - name: Debug module path and version
      debug:
        msg: "{{ module_path }} {{ module_version }} => {{ gorename_latest.stdout }}"

    - name: Ensure gorename is present
      command: go install golang.org/x/tools/cmd/gorename@latest
      when: module_version is not defined or module_version != gorename_latest.stdout
