---
- import_playbook: "go.yml"

- name: Ensure gotests is present
  hosts: all
  tasks:
    - name: Check if gotests is installed
      shell: go version -m $(command -v gotests) | grep '^\s*mod\s'
      register: gotests_installed
      ignore_errors: yes
      changed_when: False

    - name: Extract module path
      set_fact:
        module_path: "{{ gotests_installed.stdout.split()[1] }}"
        module_version: "{{ gotests_installed.stdout.split()[2] }}"

    - name: Determine the latest gotests version
      command: go list -m -f "{{ '{{' }}.Version {{ '}}' }}" "{{ module_path }}@latest"
      register: gotests_latest
      ignore_errors: yes
      changed_when: False

    - name: Debug module path and version
      debug:
        msg: "{{ module_path }} {{ module_version }} => {{ gotests_latest.stdout }}"

    - name: Ensure gotests is present
      command: go install github.com/cweill/gotests/...@latest
      when: module_version is not defined or module_version != gotests_latest.stdout
