---
- import_playbook: setup-user-go-bin-directory.yml

- name: Ensure gotests is present
  hosts: all
  tasks:
    - name: Check if gotests is installed
      shell: go version -m $(command -v gotests) | grep '^\s*mod\s'
      register: gotests_installed
      ignore_errors: yes
      changed_when: False

    - name: Extract gotests version
      block:
        - name: Set gotests facts
          set_fact:
            gotests_module_path: "{{ gotests_installed.stdout.split()[1] }}"
            gotests_module_version: "{{ gotests_installed.stdout.split()[2] }}"
        - name: Determine the latest gotests version
          command: go list -m -f "{{ '{{' }}.Version {{ '}}' }}" "{{ gotests_module_path }}@latest"
          register: gotests_latest
          ignore_errors: yes
          changed_when: False

        - name: Debug module path and version
          debug:
            msg: "{{ gotests_module_path }} {{ gotests_module_version }} => {{ gotests_latest.stdout }}"
      rescue:
        - name: Clear gotests facts
          set_fact:
            gotests_module_path: ""
            gotests_module_version: ""

    - name: Upgrade gotests
      command: go install github.com/cweill/gotests/...@latest
      when: gotests_module_version is not defined or gotests_module_version == "" or gotests_module_version != gotests_latest.stdout
