---
- import_playbook: gpg.yml
- name: Ensure gpg-agent is present
  hosts: all
  tasks:
    - name: Include guard for gpg-agent playbook
      block:
        - name: Stop early if the gpg-agent playbook is already included
          meta: end_play
          when: gpg_agent_playbook_imported is defined
        - name: Ensure the gpg-agent playbook is not included
          set_fact:
            gpg_agent_playbook_imported: true
          when: gpg_agent_playbook_imported is not defined

    - name: Ensure gpg-agent is present on MacOS
      community.general.homebrew:
        name: gnupg
        state: present
      when: ansible_facts['os_family'] == "Darwin"

    - name: Ensure gpg-agent is present on non-Termux, non-MacOS systems
      package:
        name: gpg-agent
        state: present
      when: ansible_env.TERMUX_VERSION is not defined and ansible_facts['os_family'] != "Darwin"
      become: yes

    - name: Ensure gpg-agent is present on Termux
      block:
        - name: Check if gpg-agent is installed
          shell: command -v gpg-agent
          changed_when: False
      rescue:
        - name: Install gpg-agent on Termux
          command: pkg install -y gpg-agent
      when: ansible_env.TERMUX_VERSION is defined
