---
- name: Ensure gpg is present
  hosts: all
  tasks:
    - name: Include guard for gpg playbook
      block:
        - name: Stop early if the gpg playbook is already included
          meta: end_play
          when: gpg_playbook_imported is defined
        - name: Ensure the gpg playbook is not included
          set_fact:
            gpg_playbook_imported: true
          when: gpg_playbook_imported is not defined

    - name: Ensure gpg is present on non-Termux systems
      package:
        name: gpg
        state: present
      when: ansible_env.TERMUX_VERSION is not defined
      become: yes

    - name: Ensure gpg is present on Termux
      block:
        - name: Check if gpg is installed
          shell: command -v gpg
          changed_when: False
      rescue:
        - name: Install gpg on Termux
          command: pkg install -y gpg
      when: ansible_env.TERMUX_VERSION is defined
