---
- name: Ensure grep is present
  hosts: all
  tasks:
    - name: Include guard for grep playbook
      block:
        - name: Stop early if the grep playbook is already included
          meta: end_play
          when: grep_playbook_imported is defined
        - name: Ensure the grep playbook is not included
          set_fact:
            grep_playbook_imported: true
          when: grep_playbook_imported is not defined

    - name: Ensure grep is present on non-Termux systems
      package:
        name: grep
        state: present
      when: ansible_env.TERMUX_VERSION is not defined
      become: yes

    - name: Ensure grep is present on Termux
      block:
        - name: Check if grep is installed
          shell: command -v grep
          changed_when: False
      rescue:
        - name: Install grep on Termux
          command: pkg install -y grep
      when: ansible_env.TERMUX_VERSION is defined
