---
- import_playbook: "go.yml"

- name: Ensure image2ascii is present
  hosts: all
  tasks:
    - name: Check if image2ascii is installed
      shell: go version -m $(command -v image2ascii) | grep '^\s*mod\s'
      register: image2ascii_installed
      ignore_errors: yes
      changed_when: False

    - name: Extract image2ascii version
      block:
        - name: Set image2ascii facts
          set_fact:
            image2ascii_module_path: "{{ image2ascii_installed.stdout.split()[1] }}"
            image2ascii_module_version: "{{ image2ascii_installed.stdout.split()[2] }}"
        - name: Determine the latest image2ascii version
          command: go list -m -f "{{ '{{' }}.Version {{ '}}' }}" "{{ image2ascii_module_path }}@latest"
          register: image2ascii_latest
          ignore_errors: yes
          changed_when: False

        - name: Debug module path and version
          debug:
            msg: "{{ image2ascii_module_path }} {{ image2ascii_module_version }} => {{ image2ascii_latest.stdout }}"
      rescue:
        - name: Clear image2ascii facts
          set_fact:
            image2ascii_module_path: ""
            image2ascii_module_version: ""

    - name: Upgrade image2ascii
      command: go install github.com/qeesung/image2ascii@latest
      when: image2ascii_module_version is not defined or image2ascii_module_version == "" or image2ascii_module_version != image2ascii_latest.stdout
