---
- import_playbook: "go.yml"

- name: Ensure impl is present
  hosts: all
  tasks:
    - name: Check if impl is installed
      shell: go version -m $(command -v impl) | grep '^\s*mod\s'
      register: impl_installed
      ignore_errors: yes
      changed_when: False

    - name: Extract impl version
      block:
        - name: Set impl facts
          set_fact:
            impl_module_path: "{{ impl_installed.stdout.split()[1] }}"
            impl_module_version: "{{ impl_installed.stdout.split()[2] }}"
        - name: Determine the latest impl version
          command: go list -m -f "{{ '{{' }}.Version {{ '}}' }}" "{{ impl_module_path }}@latest"
          register: impl_latest
          ignore_errors: yes
          changed_when: False

        - name: Debug module path and version
          debug:
            msg: "{{ impl_module_path }} {{ impl_module_version }} => {{ impl_latest.stdout }}"
      rescue:
        - name: Clear impl facts
          set_fact:
            impl_module_path: ""
            impl_module_version: ""

    - name: Upgrade impl
      command: go install github.com/josharian/impl@latest
      when: impl_module_version is not defined or impl_module_version == "" or impl_module_version != impl_latest.stdout
