---
- name: Ensure jq is present
  hosts: all
  tasks:
    - name: Include guard for jq playbook
      block:
        - name: Stop early if the jq playbook is already included
          meta: end_play
          when: jq_playbook_imported is defined
        - name: Ensure the jq playbook is not included
          set_fact:
            jq_playbook_imported: true
          when: jq_playbook_imported is not defined

    - name: Ensure jq is present on MacOS
      block:
        - name: Check if jq is installed
          shell: command -v jq
          changed_when: False
      rescue:
        - name: Install jq on MacOS
          community.general.homebrew:
            name: jq
            state: present
      when: ansible_facts['os_family'] == "Darwin"

    - name: Ensure jq is present on non-Termux, non-MacOS systems
      block:
        - name: Check if jq is installed
          shell: command -v jq
          changed_when: False
      rescue:
        - name: Install jq on non-Termux, non-MacOS systems
          package:
            name: jq
            state: present
          become: yes
      when: ansible_env.TERMUX_VERSION is not defined and ansible_facts['os_family'] != "Darwin"

    - name: Ensure jq is present on Termux
      block:
        - name: Check if jq is installed
          shell: command -v jq
          changed_when: False
      rescue:
        - name: Install jq on Termux
          command: pkg install -y jq
      when: ansible_env.TERMUX_VERSION is defined
