---
- name: Ensure keychain is present
  hosts: all
  tasks:
    - name: Include guard for keychain playbook
      block:
        - name: Stop early if the keychain playbook is already included
          meta: end_play
          when: keychain_playbook_imported is defined
        - name: Ensure the keychain playbook is not included
          set_fact:
            keychain_playbook_imported: true
          when: keychain_playbook_imported is not defined

    - name: Ensure keychain is present on non-Termux systems
      package:
        name: keychain
        state: present
      when: ansible_env.TERMUX_VERSION is not defined
      become: yes

    - name: Ensure keychain is present on Termux
      block:
        - name: Check if keychain is installed
          shell: command -v keychain
          changed_when: False
      rescue:
        - name: Install keychain on Termux
          command: pkg install -y keychain
      when: ansible_env.TERMUX_VERSION is defined
