---
- name: Ensure locate is present
  hosts: all
  tasks:
    - name: Include guard for locate playbook
      block:
        - name: Stop early if the locate playbook is already included
          meta: end_play
          when: locate_playbook_imported is defined
        - name: Ensure the locate playbook is not included
          set_fact:
            locate_playbook_imported: true
          when: locate_playbook_imported is not defined

    - name: Ensure locate is present on MacOS
      block:
        - name: Check if locate is installed
          shell: command -v locate
          changed_when: False
      rescue:
        - name: Install locate on MacOS
          community.general.homebrew:
            name: findutils
            state: present
      when: ansible_facts['os_family'] == "Darwin"

    - name: Ensure locate is present on non-Termux, non-MacOS systems
      block:
        - name: Check if locate is installed
          shell: command -v locate
          changed_when: False
      rescue:
        - name: Install locate on non-Termux, non-MacOS systems
          package:
            name: mlocate
            state: present
          become: yes
      when: ansible_env.TERMUX_VERSION is not defined and ansible_facts['os_family'] != "Darwin"

    - name: Ensure locate is present on Termux
      block:
        - name: Check if locate is installed
          shell: command -v locate
          changed_when: False
      rescue:
        - name: Install locate on Termux
          command: pkg install -y mlocate
      when: ansible_env.TERMUX_VERSION is defined

    - name: Ensure locate DB is up-to-date on non-macOS systems
      command: updatedb
      become: "{{ 'no' if ansible_env.TERMUX_VERSION is defined else 'yes' }}"
      when: ansible_facts['os_family'] != "Darwin"

    - name: Note about locate DB on macOS
      debug:
        msg: "On macOS, run 'sudo /usr/libexec/locate.updatedb' manually to update the locate database"
      when: ansible_facts['os_family'] == "Darwin"
