---
- name: Ensure npm is present
  hosts: all
  tasks:
    - name: Include guard for npm playbook
      block:
        - name: Stop early if the npm playbook is already included
          meta: end_play
          when: npm_playbook_imported is defined
        - name: Ensure the npm playbook is not included
          set_fact:
            npm_playbook_imported: true
          when: npm_playbook_imported is not defined

    - name: Ensure npm is present on MacOS
      community.general.homebrew:
        name: node
        state: present
      when: ansible_facts['os_family'] == "Darwin"

    - name: Ensure npm is present on non-Termux, non-MacOS systems
      block:
        - name: Check if npm is installed
          shell: command -v npm
          changed_when: False
      rescue:
        - name: Install npm on non-Termux, non-MacOS systems
          package:
            name: npm
            state: present
          become: yes
      when: ansible_env.TERMUX_VERSION is not defined and ansible_facts['os_family'] != "Darwin"

    - name: Ensure npm is present on Termux
      block:
        - name: Check if npm is installed
          shell: command -v npm
          changed_when: False
      rescue:
        - name: Install npm on Termux
          command: pkg install -y nodejs
      when: ansible_env.TERMUX_VERSION is defined
