---
- name: Ensure pandoc is present
  hosts: all
  tasks:
    - name: Include guard for pandoc playbook
      block:
        - name: Stop early if the pandoc playbook is already included
          meta: end_play
          when: pandoc_playbook_imported is defined
        - name: Ensure the pandoc playbook is not included
          set_fact:
            pandoc_playbook_imported: true
          when: pandoc_playbook_imported is not defined

    - name: Ensure pandoc is present on MacOS
      block:
        - name: Check if pandoc is installed
          shell: command -v pandoc
          changed_when: False
      rescue:
        - name: Install pandoc on MacOS
          community.general.homebrew:
            name: pandoc
            state: present
      when: ansible_facts['os_family'] == "Darwin"

    - name: Ensure pandoc is present on non-Termux, non-MacOS systems
      block:
        - name: Check if pandoc is installed
          shell: command -v pandoc
          changed_when: False
      rescue:
        - name: Install pandoc on non-Termux, non-MacOS systems
          package:
            name: pandoc
            state: present
          become: yes
      when: ansible_env.TERMUX_VERSION is not defined and ansible_facts['os_family'] != "Darwin"

    - name: Ensure pandoc is present on Termux
      block:
        - name: Check if pandoc is installed
          shell: command -v pandoc
          changed_when: False
      rescue:
        - name: Install pandoc on Termux
          command: pkg install -y pandoc
      when: ansible_env.TERMUX_VERSION is defined
