---
- name: Ensure pass is present
  hosts: all
  tasks:
    - name: Include guard for pass playbook
      block:
        - name: Stop early if the pass playbook is already included
          meta: end_play
          when: pass_playbook_imported is defined
        - name: Ensure the pass playbook is not included
          set_fact:
            pass_playbook_imported: true
          when: pass_playbook_imported is not defined

    - name: Ensure pass is present on MacOS
      block:
        - name: Check if pass is installed
          shell: command -v pass
          changed_when: False
      rescue:
        - name: Install pass on MacOS
          community.general.homebrew:
            name: pass
            state: present
      when: ansible_facts['os_family'] == "Darwin"

    - name: Ensure pass is present on non-Termux, non-MacOS systems
      block:
        - name: Check if pass is installed
          shell: command -v pass
          changed_when: False
      rescue:
        - name: Install pass on non-Termux, non-MacOS systems
          package:
            name: pass
            state: present
          become: yes
      when: ansible_env.TERMUX_VERSION is not defined and ansible_facts['os_family'] != "Darwin"

    - name: Ensure pass is present on Termux
      block:
        - name: Check if pass is installed
          shell: command -v pass
          changed_when: False
      rescue:
        - name: Install pass on Termux
          command: pkg install -y pass
      when: ansible_env.TERMUX_VERSION is defined
