---
- import_playbook: "go.yml"

- name: Ensure protoc-gen-go-grpc is present
  hosts: all
  tasks:
    - name: Ensure protoc-gen-go-grpc is present
      command: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
