---
- name: Ensure protoc is present
  hosts: all
  tasks:
    - name: Include guard for protoc playbook
      block:
        - name: Stop early if the protoc playbook is already included
          meta: end_play
          when: protoc_playbook_imported is defined
        - name: Ensure the protoc playbook is not included
          set_fact:
            protoc_playbook_imported: true
          when: protoc_playbook_imported is not defined

    - name: Ensure protoc is present on MacOS
      block:
        - name: Check if protoc is installed
          shell: command -v protoc
          changed_when: False
      rescue:
        - name: Install protoc on MacOS
          community.general.homebrew:
            name: protobuf
            state: present
      when: ansible_facts['os_family'] == "Darwin"

    - name: Ensure protoc is present on non-Termux, non-MacOS systems
      block:
        - name: Check if protoc is installed
          shell: command -v protoc
          changed_when: False
      rescue:
        - name: Install protoc on non-Termux, non-MacOS systems
          package:
            name: protobuf-compiler
            state: present
          become: yes
      when: ansible_env.TERMUX_VERSION is not defined and ansible_facts['os_family'] != "Darwin"

    - name: Ensure protoc is present on Termux
      block:
        - name: Check if protoc is installed
          shell: command -v protoc
          changed_when: False
      rescue:
        - name: Install protoc on Termux
          command: pkg install -y protobuf
      when: ansible_env.TERMUX_VERSION is defined
