---
- name: Ensure python3-notmuch2 is present
  hosts: all
  tasks:
    - name: Include guard for python3-notmuch2 playbook
      block:
        - name: Stop early if the python3-notmuch2 playbook is already included
          meta: end_play
          when: python3-notmuch2_playbook_imported is defined
        - name: Ensure the python3-notmuch2 playbook is not included
          set_fact:
            python3-notmuch2_playbook_imported: true
          when: python3-notmuch2_playbook_imported is not defined

    - name: Ensure python3-notmuch2 is present on non-Termux systems
      package:
        name: python3-notmuch2
        state: present
      when: ansible_env.TERMUX_VERSION is not defined
      become: yes

    - name: Ensure python3-notmuch2 is present on Termux
      block:
        - name: Check if python3-notmuch2 is installed
          shell: command -v python3-notmuch2
          changed_when: False
      rescue:
        - name: Install python3-notmuch2 on Termux
          command: pkg install -y notmuch
      when: ansible_env.TERMUX_VERSION is defined
