---
- import_playbook: emacs.yml
- import_playbook: e.yml

- name: Ensure emacs is properly set up
  hosts: all
  tasks:
    - name: Include guard for setup-emacs playbook
      block:
        - name: Stop early if the setup-emacs playbook is already included
          meta: end_play
          when: setup_emacs_playbook_imported is defined
        - name: Ensure the setup-emacs playbook is not included
          set_fact:
            setup_emacs_playbook_imported: true
          when: setup_emacs_playbook_imported is not defined

    - name: Ensure editor environment variable
      ansible.builtin.blockinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        append_newline: true
        prepend_newline: true
        create: true
        marker: "# {mark} emacs editor environment variable"
        block: |
          export EDITOR="emacsclient -a ''"
