---
- import_playbook: emacs-lsp-booster.yml
- import_playbook: setup-shell-profile.yml

- name: Ensure emacs-lsp-booster is properly set up
  hosts: all
  tasks:
    - name: Include guard for setup-emacs-lsp-booster playbook
      block:
        - name: Stop early if the setup-emacs-lsp-booster playbook is already included
          meta: end_play
          when: setup_emacs_lsp_booster_playbook_imported is defined
        - name: Ensure the setup-emacs-lsp-booster playbook is not included
          set_fact:
            setup_emacs_lsp_booster_playbook_imported: true
          when: setup_emacs_lsp_booster_playbook_imported is not defined

    - name: Ensure LSP_USE_PLISTS environment variable is set
      ansible.builtin.blockinfile:
        path: "{{ user_profile_path }}"
        append_newline: true
        prepend_newline: true
        create: true
        marker: "# {mark} emacs-lsp-booster environment variable"
        block: |
          export LSP_USE_PLISTS=true
