---
- import_playbook: zoxide.yml
- import_playbook: setup-starship.yml
- import_playbook: setup-shell-profile.yml

- name: Ensure z directory jumping with zoxide and starship
  hosts: all
  tasks:
    - name: Include guard for setup-z playbook
      block:
        - name: Stop early if the setup-z playbook is already included
          meta: end_play
          when: setup_z_playbook_imported is defined
        - name: Ensure the setup-z playbook is not included
          set_fact:
            setup_z_playbook_imported: true
          when: setup_z_playbook_imported is not defined

    - name: Configure zoxide in shell profile
      ansible.builtin.blockinfile:
        path: "{{ user_profile_path }}"
        append_newline: true
        prepend_newline: true
        create: true
        marker: "# {mark} Enable zoxide"
        block: |
          if command -v zoxide >/dev/null 2>&1; then
              eval "$(zoxide init {{ user_shell.stdout | basename }})"
          fi
