---
- import_playbook: setup-emacs.yml
- import_playbook: spacemacs.yml
- import_playbook: rg.yml
- import_playbook: pandoc.yml

- name: Ensure spacemacs is properly set up
  hosts: all
  tasks:
    - name: Include guard for setup-spacemacs playbook
      block:
        - name: Stop early if the setup-spacemacs playbook is already included
          meta: end_play
          when: setup_spacemacs_playbook_imported is defined
        - name: Ensure the setup-spacemacs playbook is not included
          set_fact:
            setup_spacemacs_playbook_imported: true
          when: setup_spacemacs_playbook_imported is not defined

    - name: Ensure vterm directory tracking
      ansible.builtin.blockinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        append_newline: true
        prepend_newline: true
        create: true
        marker: "# {mark} vterm directory tracking"
        block: |
          if [[ "$INSIDE_EMACS" = "vterm" ]] \
                 && [[ -n ${EMACS_VTERM_PATH} ]] \
                 && [[ -f ${EMACS_VTERM_PATH}/etc/emacs-vterm-bash.sh ]]; then
              source ${EMACS_VTERM_PATH}/etc/emacs-vterm-bash.sh
          fi
