---
- import_playbook: setup-user-bin-directory.yml
- import_playbook: setup-shell-profile.yml

- name: Ensure z is set property
  hosts: all
  tasks:
    - name: Include guard for setup-z playbook
      block:
        - name: Stop early if the setup-z playbook is already included
          meta: end_play
          when: setup_z_playbook_imported is defined
        - name: Ensure the setup-z playbook is not included
          set_fact:
            setup_z_playbook_imported: true
          when: setup_z_playbook_imported is not defined

    - block:
      - name: Ensure z.sh is downloaded.
        ansible.builtin.get_url:
          url: https://raw.githubusercontent.com/rupa/z/master/z.sh
          dest: "{{ ansible_env.HOME }}/.local/bin/z.sh"
          mode: '0700'

      - name: Ensure z.sh is properly set in shell profile
        ansible.builtin.blockinfile:
          path: "{{ user_profile_path }}"
          append_newline: true
          prepend_newline: true
          create: true
          marker: "# {mark} Enable z script"
          block: |
            if [ -f ~/.local/bin/z.sh ]; then
                . ~/.local/bin/z.sh
                {% if user_shell.stdout is search('/bash$') %}
                PROMPT_COMMAND="${PROMPT_COMMAND%;}"
                {% endif %}
            fi
      when: ansible_facts['os_family'] != "Darwin"
