---
- name: Ensure the user config directory exists
  hosts: all
  tasks:
    - name: Include guard for setup-user-config-directory playbook
      block:
        - name: Stop early if the setup-user-config-directory playbook is already included
          meta: end_play
          when: setup_user_config_directory_playbook_imported is defined
        - name: Ensure the setup-user-config-directory playbook is not included
          set_fact:
            setup_user_config_directory_playbook_imported: true
          when: setup_user_config_directory_playbook_imported is not defined

    - name: Determine the user config directory
      ansible.builtin.set_fact:
        user_config_directory: "{{ ansible_env.XDG_CONFIG_HOME | default(ansible_env.HOME + '/.config') }}"

    - name: Ensure the user config directory exists
      ansible.builtin.file:
        path: "{{ user_config_directory }}"
        state: directory
        mode: '0700'

    - name: Debug output of the user config directory
      ansible.builtin.debug:
        msg: "The config directory is {{ user_config_directory }}"
