---
- name: Ensure ssh is present
  hosts: all
  tasks:
    - name: Include guard for ssh playbook
      block:
        - name: Stop early if the ssh playbook is already included
          meta: end_play
          when: ssh_playbook_imported is defined
        - name: Ensure the ssh playbook is not included
          set_fact:
            ssh_playbook_imported: true
          when: ssh_playbook_imported is not defined

    - name: Ensure ssh is present on MacOS
      community.general.homebrew:
        name: ssh
        state: present
      when: ansible_facts['os_family'] == "Darwin"

    - name: Ensure ssh is present on non-Termux, non-MacOS systems
      package:
        name: openssh-client
        state: present
      when: ansible_env.TERMUX_VERSION is not defined and ansible_facts['os_family'] != "Darwin"
      become: yes

    - name: Ensure ssh is present on Termux
      block:
        - name: Check if ssh is installed
          shell: command -v ssh
          changed_when: False
      rescue:
        - name: Install ssh on Termux
          command: pkg install -y openssh
      when: ansible_env.TERMUX_VERSION is defined
