---
- name: Ensure sshpass is present
  hosts: all
  tasks:
    - name: Ensure sshpass is present on non-Termux systems
      package:
        name: sshpass
        state: present
      when: ansible_env.TERMUX_VERSION is not defined
      become: yes

    - name: Ensure sshpass is present on Termux
      block:
        - name: Check if sshpass is installed
          shell: command -v sshpass
          changed_when: False
      rescue:
        - name: Install sshpass on Termux
          command: pkg install -y sshpass
      when: ansible_env.TERMUX_VERSION is defined
