---

- name: Ensure starship is present
  hosts: all
  tasks:
    - name: Include guard for starship playbook
      block:
        - name: Stop early if the starship playbook is already included
          meta: end_play
          when: starship_playbook_imported is defined
        - name: Ensure the starship playbook is not included
          set_fact:
            starship_playbook_imported: true
          when: starship_playbook_imported is not defined

    - name: Ensure starship is present on MacOS
      block:
        - name: Check if starship is installed
          shell: command -v starship
          changed_when: False
      rescue:
        - name: Install starship on MacOS
          community.general.homebrew:
            name: starship
            state: present
      when: ansible_facts['os_family'] == "Darwin"

    - name: Ensure starship is present on Termux
      block:
        - name: Check if starship is installed
          shell: command -v starship
          changed_when: False
      rescue:
        - name: Install starship on Termux
          command: pkg install -y starship
      when: ansible_env.TERMUX_VERSION is defined

    - name: Install starship via shell on Debian/Ubuntu
      block:
        - name: Get installed starship version
          command: starship --version
          register: starship_version_output
          failed_when: false
          changed_when: False

        - name: Parse installed starship version
          set_fact:
            starship_installed_version: "{{ starship_version_output.stdout | regex_search('starship ([0-9.]+)', '\\1') | default('0.0.0') | first }}"

        - name: Get latest available starship version from GitHub
          uri:
            url: https://api.github.com/repos/starship/starship/releases/latest
            return_content: yes
          register: starship_latest_release

        - name: Parse latest starship version from GitHub response
          set_fact:
            starship_latest_version: "{{ starship_latest_release.json.tag_name | regex_replace('^v', '') }}"

        - name: Install/update starship if outdated
          shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
          when: starship_installed_version != starship_latest_version
      when: ansible_env.TERMUX_VERSION is not defined and ansible_facts['os_family'] != "Darwin"
