---
- import_playbook: setup-cargo.yml
- import_playbook: cargo-install-update.yml

- name: Ensure starship is present
  hosts: all
  tasks:
    - name: Include guard for starship playbook
      block:
        - name: Stop early if the starship playbook is already included
          meta: end_play
          when: starship_playbook_imported is defined
        - name: Ensure the starship playbook is not included
          set_fact:
            starship_playbook_imported: true
          when: starship_playbook_imported is not defined

    - name: Check if starship is installed
      shell: command -v starship
      register: starship_installed
      ignore_errors: yes
      changed_when: False

    - name: Install starship using Cargo
      command: cargo install starship
      when: starship_installed.rc != 0

    - name: Update starship to latest version
      command: cargo install-update starship
      register: starship_update_result
      changed_when: "starship_update_result.stdout is search('Overall updated [1-9]')"
      when: starship_installed.rc == 0
