package main

const (
	WhenDarwin     = `ansible_facts['os_family'] == "Darwin"`
	WhenNotDarwin  = `ansible_facts['os_family'] != "Darwin"`
	WhenTermux     = `ansible_env.TERMUX_VERSION is defined`
	WhenNotTermux  = `ansible_env.TERMUX_VERSION is not defined`
	WhenDebianLike = `ansible_env.TERMUX_VERSION is not defined and ansible_facts['os_family'] != "Darwin"`
	WhenUbuntu     = `ansible_facts['distribution'] == "Ubuntu"`
)

var packagesTemplate = `---
# THIS FILE IS AUTO-GENERATED by generate_packages.go - DO NOT EDIT MANUALLY
# To make changes, modify generate_packages.go, install_methods.go, packages_data.go, or templates.go
# and then run: make
{{- range .Imports }}
- import_playbook: {{.Playbook}}.yml{{if .When}}
  when: {{.When}}{{end}}
{{- end }}
- name: Ensure {{.Command}} is present
  hosts: all
  tasks:
    - name: Include guard for {{.Command}} playbook
      block:
        - name: Stop early if the {{.Command}} playbook is already included
          meta: end_play
          when: {{.CommandID}}_playbook_imported is defined
        - name: Ensure the {{.Command}} playbook is not included
          set_fact:
            {{.CommandID}}_playbook_imported: true
          when: {{.CommandID}}_playbook_imported is not defined
{{ if .UbuntuPPA }}
    - name: Ensure {{.Command}} PPA is present in Ubuntu
      apt_repository:
        repo: "{{.UbuntuPPA}}"
        state: present
        update_cache: yes
      when: ` + WhenDebianLike + ` and ` + WhenUbuntu + `
      become: yes

    - name: Ensure bookworm-backports is added to sources.list.d
      ansible.builtin.apt_repository:
        repo: "deb http://deb.debian.org/debian bookworm-backports main contrib non-free non-free-firmware"
        state: present
        update_cache: yes
      when: ` + WhenDebianLike + ` and ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "12"
      become: yes
{{ end }}{{ if .BrewTap }}
    - name: Tap {{.BrewTap}} for {{.Command}}
      community.general.homebrew_tap:
        name: {{.BrewTap}}
        state: present
      when: ` + WhenDarwin + `
{{ end }}
    - name: Ensure {{.Command}} is present on MacOS
      block:
        - name: Check if {{.Command}} is installed
          shell: command -v {{.Command}}
          changed_when: False
      rescue:
        - name: Install {{.Command}} on MacOS
          community.general.homebrew:
            name: {{.BrewPkgName}}
            state: present{{ if .BrewOptions }}
            install_options:{{ range .BrewOptions }}
              - {{ . }}{{ end }}{{ end }}
      when: ` + WhenDarwin + `

    - name: Ensure {{.Command}} is present on non-Termux, non-MacOS systems
      block:
        - name: Check if {{.Command}} is installed
          shell: command -v {{.Command}}
          changed_when: False
      rescue:
        - name: Install {{.Command}} on non-Termux, non-MacOS systems
          package:
            name: {{.DebianPkgName}}
            state: present
          become: yes
      when: ` + WhenDebianLike + `

    - name: Ensure {{.Command}} is present on Termux
      block:
        - name: Check if {{.Command}} is installed
          shell: command -v {{.Command}}
          changed_when: False
      rescue:
        - name: Install {{.Command}} on Termux
          command: pkg install -y {{.TermuxPkgName}}
      when: ` + WhenTermux + `{{.Suffix}}
`

var platformSpecificTemplate = `---
# THIS FILE IS AUTO-GENERATED by generate_packages.go - DO NOT EDIT MANUALLY
# To make changes, modify generate_packages.go, install_methods.go, packages_data.go, or templates.go
# and then run: make
{{- range .GetAllImports }}
- import_playbook: {{.Playbook}}.yml{{if .When}}
  when: {{.When}}{{end}}
{{- end }}

- name: Ensure {{.Command}} is present
  hosts: all
  tasks:
    - name: Include guard for {{.Command}} playbook
      block:
        - name: Stop early if the {{.Command}} playbook is already included
          meta: end_play
          when: {{.CommandID}}_playbook_imported is defined
        - name: Ensure the {{.Command}} playbook is not included
          set_fact:
            {{.CommandID}}_playbook_imported: true
          when: {{.CommandID}}_playbook_imported is not defined
{{- if .HasDarwin }}
{{- $method := .DarwinMethod }}
{{- $setupTasks := $method.RenderSetupTasks .Command }}
{{- if $setupTasks }}

{{$setupTasks}}
{{- end }}

    - name: Ensure {{.Command}} is present on MacOS
      block:
{{$method.RenderBlockInstallTask .Command}}
      when: ` + WhenDarwin + `
{{- end }}
{{- if .HasTermux }}
{{- $method := .TermuxMethod }}

    - name: Ensure {{.Command}} is present on Termux
      block:
{{$method.RenderBlockInstallTask .Command}}
      when: ` + WhenTermux + `
{{- end }}
{{- if .HasAll }}
{{- $method := .AllMethod }}

{{$method.RenderInstallTask .Command}}
{{- else }}
{{- if .HasDebianLike }}
{{- $method := .DebianLikeMethod }}
{{- $setupTasks := $method.RenderSetupTasks .Command }}
{{- if $setupTasks }}

{{$setupTasks}}
{{- end }}
{{- if or (eq $method.GetMethodType "pip") (eq $method.GetMethodType "uv") }}

{{$method.RenderInstallTask .Command}}
      when: ` + WhenDebianLike + `
{{- else if eq $method.GetMethodType "cargo" }}

    - name: Install {{.Command}} via cargo on Debian/Ubuntu
      block:
{{$method.RenderBlockInstallTask .Command}}
      when: ` + WhenDebianLike + `
{{- else }}

    - name: Install {{.Command}} via {{$method.GetMethodType}} on Debian/Ubuntu
      block:
{{$method.RenderBlockInstallTask .Command}}
      when: ` + WhenDebianLike + `
{{- end }}
{{- else }}
{{- if .HasDebian }}
{{- $method := .DebianMethod }}

    - name: Install {{.Command}} via {{$method.GetMethodType}} on Debian
{{$method.RenderInstallTask .Command}}
      when: ` + WhenDebianLike + ` and ansible_facts['distribution'] == "Debian"
{{- end }}
{{- if .HasUbuntu }}
{{- $method := .UbuntuMethod }}

    - name: Install {{.Command}} via {{$method.GetMethodType}} on Ubuntu
{{$method.RenderInstallTask .Command}}
      when: ` + WhenDebianLike + ` and ` + WhenUbuntu + `
{{- end }}
{{- end }}
{{- end }}
`
