---
- name: Ensure unzip is present
  hosts: all
  tasks:
    - name: Include guard for unzip playbook
      block:
        - name: Stop early if the unzip playbook is already included
          meta: end_play
          when: unzip_playbook_imported is defined
        - name: Ensure the unzip playbook is not included
          set_fact:
            unzip_playbook_imported: true
          when: unzip_playbook_imported is not defined

    - name: Ensure unzip is present on MacOS
      block:
        - name: Check if unzip is installed
          shell: command -v unzip
          changed_when: False
      rescue:
        - name: Install unzip on MacOS
          community.general.homebrew:
            name: unzip
            state: present
      when: ansible_facts['os_family'] == "Darwin"

    - name: Ensure unzip is present on non-Termux, non-MacOS systems
      block:
        - name: Check if unzip is installed
          shell: command -v unzip
          changed_when: False
      rescue:
        - name: Install unzip on non-Termux, non-MacOS systems
          package:
            name: unzip
            state: present
          become: yes
      when: ansible_env.TERMUX_VERSION is not defined and ansible_facts['os_family'] != "Darwin"

    - name: Ensure unzip is present on Termux
      block:
        - name: Check if unzip is installed
          shell: command -v unzip
          changed_when: False
      rescue:
        - name: Install unzip on Termux
          command: pkg install -y unzip
      when: ansible_env.TERMUX_VERSION is defined
