---

- name: Ensure uv is present
  hosts: all
  tasks:
    - name: Include guard for uv playbook
      block:
        - name: Stop early if the uv playbook is already included
          meta: end_play
          when: uv_playbook_imported is defined
        - name: Ensure the uv playbook is not included
          set_fact:
            uv_playbook_imported: true
          when: uv_playbook_imported is not defined

    - name: Ensure uv is present on MacOS
      block:
        - name: Check if uv is installed
          shell: command -v uv
          changed_when: False
      rescue:
        - name: Install uv on MacOS
          community.general.homebrew:
            name: uv
            state: present
      when: ansible_facts['os_family'] == "Darwin"

    - name: Ensure uv is present on Termux
      block:
        - name: Check if uv is installed
          shell: command -v uv
          changed_when: False
      rescue:
        - name: Install uv on Termux
          command: pkg install -y uv
      when: ansible_env.TERMUX_VERSION is defined

    - name: Install uv via shell on Debian/Ubuntu
      block:
        - name: Check if uv is installed
          shell: command -v uv
          register: uv_installed
          failed_when: false
          changed_when: False

        - name: Install uv
          shell: curl -LsSf https://astral.sh/uv/install.sh | sh
          when: uv_installed.rc != 0
      when: ansible_env.TERMUX_VERSION is not defined and ansible_facts['os_family'] != "Darwin"
