---
- name: Ensure vipsthumbnail is present
  hosts: all
  tasks:
    - name: Include guard for vipsthumbnail playbook
      block:
        - name: Stop early if the vipsthumbnail playbook is already included
          meta: end_play
          when: vipsthumbnail_playbook_imported is defined
        - name: Ensure the vipsthumbnail playbook is not included
          set_fact:
            vipsthumbnail_playbook_imported: true
          when: vipsthumbnail_playbook_imported is not defined

    - name: Ensure vipsthumbnail is present on MacOS
      block:
        - name: Check if vipsthumbnail is installed
          shell: command -v vipsthumbnail
          changed_when: False
      rescue:
        - name: Install vipsthumbnail on MacOS
          community.general.homebrew:
            name: vips
            state: present
      when: ansible_facts['os_family'] == "Darwin"

    - name: Ensure vipsthumbnail is present on non-Termux, non-MacOS systems
      block:
        - name: Check if vipsthumbnail is installed
          shell: command -v vipsthumbnail
          changed_when: False
      rescue:
        - name: Install vipsthumbnail on non-Termux, non-MacOS systems
          package:
            name: libvips-tools
            state: present
          become: yes
      when: ansible_env.TERMUX_VERSION is not defined and ansible_facts['os_family'] != "Darwin"

    - name: Ensure vipsthumbnail is present on Termux
      block:
        - name: Check if vipsthumbnail is installed
          shell: command -v vipsthumbnail
          changed_when: False
      rescue:
        - name: Install vipsthumbnail on Termux
          command: pkg install -y libvips
      when: ansible_env.TERMUX_VERSION is defined
