name: Emacs Init Test

on:
  push:
    branches: [ main ]
    paths: '.spacemacs'
  pull_request:
    branches: [ main ]
    paths: '.spacemacs'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: purcell/setup-emacs@master
        with:
          version: 29.4
      - name: Build
        run: make
        working-directory: spacemacs/
